### ISSUE TITLE
Is this module still maintained?

### ISSUE THREAD

**Issue by tyemirov** [jpowers/node-google-places#1]
We would love to use the module if it is still maintained. Currently even the example provided fails -- are there plans to revive the project?

**Comment by jpowers** [comment]
Yes, I'll take a look at it. Google may have changed things.

**Comment by tyemirov** [comment]
Thanks a mil.

The issue I was experiencing was related to the fact that the public IP hasn't been added to Google API Key. In which case the module returns no error but just gives empty result set, which, I thought, is not an expected behavior in case of an error ...

**Comment by jpowers** [comment]
The example seems to work for me.  Are you using your api key?  Could you provide the code you are trying?

**Comment by tyemirov** [comment]
Sorry if I was unclear. If the there is an issue with the API key, e.g. Google denies it, the module doesn't return an error, as I expect it would.

**Comment by rahul** [comment]
I created a server key and followed your example. I still keep getting "REQUEST_DENIED" though in the Google API console, the requests count keep increasing.

I only changed the params sent to GooglePlaces.search() from {keyword: 'Vermonster'} to {keyword: 'bar', location: [someLat, someLng]}

**Comment by rahul** [comment]
Resolved: https://github.com/moshen/node-googlemaps/issues/12#issuecomment-6764839
